package com.bonbonite.qa.web.ecommerce.pages;

import com.bonbonite.qa.web.pages.WebBaseScreen;
import java.util.List;
import lombok.Getter;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

/**
 * Locators of the customer service request screen.
 *
 * <p>The form is generated by a plugin that appends a render identifier to every
 * element id, and that identifier changes on each page load. Locating by id would
 * therefore break on the very next execution, so every field is located by its
 * {@code name} attribute, which is stable.</p>
 */
@Getter
public class PqrsPage extends WebBaseScreen {

  @FindBy(css = "form.forminator-custom-form")
  private WebElement frmPqrs;

  @FindBy(css = "select[name='select-1']")
  private WebElement ddlSalesPoint;

  @FindBy(css = "input[name='name-1']")
  private WebElement txtFullName;

  @FindBy(css = "input[name='address-1-street_address']")
  private WebElement txtAddress;

  @FindBy(css = "select[name='select-2']")
  private WebElement ddlDocumentType;

  @FindBy(css = "input[name='text-1']")
  private WebElement txtDocumentNumber;

  @FindBy(css = "input[name='phone-1']")
  private WebElement txtPhone;

  @FindBy(css = "input[name='email-1']")
  private WebElement txtEmail;

  @FindBy(css = "select[name='select-3']")
  private WebElement ddlRequestType;

  @FindBy(css = "select[name='select-4']")
  private WebElement ddlReason;

  @FindBy(css = "textarea[name='textarea-1']")
  private WebElement txtDescription;

  @FindBy(css = "input[name='consent-1']")
  private WebElement chkConsent;

  @FindBy(css = "button.forminator-button-submit")
  private WebElement btnSubmit;

  @FindBy(css = ".forminator-error-message, .forminator-label--error")
  private List<WebElement> lstValidationMessages;
}
