package com.bonbonite.qa.web.ecommerce.pages.components;

import com.bonbonite.qa.web.pages.WebBaseComponent;
import lombok.Getter;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

/**
 * Fixed header of the site, holding the catalog navigation, the account access and
 * the cart.
 *
 * <p>The site renders two headers at the same time in the document: one for desktop,
 * inside an {@code lg:block} block, and one for mobile inside an {@code lg:hidden}
 * block. Only one of them is visible depending on the window width, but both exist
 * in the DOM and share class names. That is why every locator is anchored explicitly
 * to the desktop container, which is the one matching the default window size.
 * Relying on document order would make the test fail intermittently against a hidden
 * element.</p>
 *
 * <p>Category links are located by their URL rather than by the numeric identifier
 * generated by the content manager, because that identifier changes if somebody
 * reorders the menu from the admin panel and would break the tests without the site
 * having changed for the user.</p>
 */
@Getter
public class HeaderComponent extends WebBaseComponent {

  private static final String DESKTOP_HEADER = "header div[class*='lg:block'] ";

  @FindBy(css = "ul#menu-categories-menu")
  private WebElement lstMainMenu;

  @FindBy(css = "ul#menu-categories-menu a[href*='/categoria-producto/zapatos-mujer/']")
  private WebElement lnkShoes;

  @FindBy(css = "ul#menu-categories-menu a[href*='/categoria-producto/bolsos-mujer/']")
  private WebElement lnkBags;

  @FindBy(css = "ul#menu-categories-menu a[href*='/categoria-producto/cinturones-mujer/']")
  private WebElement lnkBelts;

  @FindBy(css = "ul#menu-categories-menu a[href*='/categoria-producto/accesorios-mujer/']")
  private WebElement lnkAccessories;

  @FindBy(css = "ul#menu-categories-menu a[href*='/categoria-producto/outlet/']")
  private WebElement lnkOutlet;

  @FindBy(css = DESKTOP_HEADER + "a[href*='/mi-cuenta']")
  private WebElement lnkAccount;

  @FindBy(css = DESKTOP_HEADER + "a.cart-contents")
  private WebElement lnkCart;

  @FindBy(css = DESKTOP_HEADER + ".cart-contents-count")
  private WebElement lblCartCount;
}
